# Generated by Django 3.2.9 on 2021-12-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LNR_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
